// <auto-generated />
using GununAyeti.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GununAyeti.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20250304225448_VeriEklendi")]
    partial class VeriEklendi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("GununAyeti.Models.Ayet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArapcaMetin")
                        .HasColumnType("TEXT");

                    b.Property<int>("AyetNo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SureIsmi")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ayetler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aciklama = "Rahmân, Rahîm olan Allah'ın ismiyle.",
                            ArapcaMetin = "بِسْمِ اللَّهِ اَلرَّحْمٰنِ الرَّحِيمِ",
                            AyetNo = 1,
                            SureIsmi = "Fatiha"
                        },
                        new
                        {
                            Id = 2,
                            Aciklama = "Hamd, âlemlerin Rabbi(3) olan Allah'a mahsustur.",
                            ArapcaMetin = "اَلْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ",
                            AyetNo = 2,
                            SureIsmi = "Fatiha"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
