// <auto-generated />
using GununAyeti.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GununAyeti.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20250304222504_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("GununAyeti.Models.Ayet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aciklama")
                        .HasColumnType("TEXT");

                    b.Property<string>("ArapcaMetin")
                        .HasColumnType("TEXT");

                    b.Property<int>("AyetNo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SureIsmi")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ayetler");
                });
#pragma warning restore 612, 618
        }
    }
}
